# =================================================================================
# Module: security/secrets_manager
# =================================================================================
# Purpose: 
#   Secure storage for sensitive credentials using AWS Secrets Manager
#
# Secrets:
#   1. RDS database password (randomly generated)
#   2. Mailgun API key (external service)
#   3. Mailgun domain (external service)
#
# Security Features:
#   - Encrypted at rest using dedicated KMS key
#   - 7-day recovery window before permanent deletion
#   - Access controlled via IAM policies
#   - Audit trail via CloudTrail
#
# Notes:
#   - DB password is auto-generated by Terraform
#   - Mailgun credentials provided via variables
#   - EC2 and Lambda retrieve secrets at runtime
# =================================================================================

# ---------------------------------------------------------------------------------
# Random Password for RDS
# ---------------------------------------------------------------------------------

resource "random_password" "db_password" {
  length  = 16
  special = true
  # Exclude problematic characters for shell scripts
  override_special = "!#$%&*()-_=+[]{}:?"
}

# ---------------------------------------------------------------------------------
# Secret: RDS Database Password
# ---------------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "db_password" {
  name                    = "${var.project_name}/${var.environment}/rds/password"
  description             = "RDS PostgreSQL database master password"
  kms_key_id              = var.kms_secrets_key_id
  recovery_window_in_days = 7

  tags = {
    Name        = "${var.project_name}-${var.environment}-db-password"
    Environment = var.environment
    Project     = var.project_name
    Service     = "RDS"
    ManagedBy   = "terraform"
  }
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db_password.result
}

# ---------------------------------------------------------------------------------
# Secret: Mailgun API Key
# ---------------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "mailgun_api_key" {
  name                    = "${var.project_name}/${var.environment}/email/mailgun-api-key"
  description             = "Mailgun API key for sending verification emails"
  kms_key_id              = var.kms_secrets_key_id
  recovery_window_in_days = 7

  tags = {
    Name        = "${var.project_name}-${var.environment}-mailgun-api-key"
    Environment = var.environment
    Project     = var.project_name
    Service     = "Email"
    ManagedBy   = "terraform"
  }
}

resource "aws_secretsmanager_secret_version" "mailgun_api_key" {
  secret_id     = aws_secretsmanager_secret.mailgun_api_key.id
  secret_string = var.mailgun_api_key
}

# ---------------------------------------------------------------------------------
# Secret: Mailgun Domain
# ---------------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "mailgun_domain" {
  name                    = "${var.project_name}/${var.environment}/email/mailgun-domain"
  description             = "Mailgun domain for sending verification emails"
  kms_key_id              = var.kms_secrets_key_id
  recovery_window_in_days = 7

  tags = {
    Name        = "${var.project_name}-${var.environment}-mailgun-domain"
    Environment = var.environment
    Project     = var.project_name
    Service     = "Email"
    ManagedBy   = "terraform"
  }
}

resource "aws_secretsmanager_secret_version" "mailgun_domain" {
  secret_id     = aws_secretsmanager_secret.mailgun_domain.id
  secret_string = var.mailgun_domain
}
